version: "3.6"

services:

  db:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - data:/app/db
    ports:
      # this is only for development purpose
      - "5342:5342"

  data-manager:
    # Building the image
    <<: &datamanager
      image: "datamanager:latest"
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "10001:10001" 
      
volumes:
  data: