version: "3.6"

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
      # - database:/app/database
    ports:
      # this is only for development purpose
      - "5432:5432"
    env_file:
      - env_file

  data-manager:
    # Building the image
    <<: &data-manager
      image: "data-manager:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10001:10001"
    env_file: 
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - migrations

  migrations:
    <<: *data-manager
    command: flask db init && flask db migrate && flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    #restart: on-failure

volumes:
  data: