version: "3.6"

services:

  data-manager:
    # Building the image
    image: "datamanager:latest"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # expose:
    #   - "10001"
    ports:
      - "10001:10001" 