version: "3.6"

services:

  data_manager_db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - data_manager_db:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "9000:5343"
    env_file:
      - env_file
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "db", "-d", "data_manager_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  data_manager_ms:
    # Building the image
    <<: &data_manager_ms
      image: "data-manager_ms:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10001:10001"
    env_file: 
      - env_file
    environment:
      - POSTGRES_HOST=data_manager_db
    depends_on:
      - data_manager_db
      - migrations

  migrations:
    <<: *data_manager_ms
    command: sh -c "flask db init && flask db migrate && flask db upgrade" 
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=data_manager_db
    depends_on:
      data_manager_db:
        condition: service_healthy

volumes:
  data_manager_db: