"""DB Creation

Revision ID: a1f7789532b9
Revises: 
Create Date: 2022-11-14 17:29:14.235457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f7789532b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mac', sa.Unicode(), nullable=False),
    sa.Column('rssi_1', sa.Integer(), nullable=True),
    sa.Column('rssi_2', sa.Integer(), nullable=True),
    sa.Column('rssi_3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Raw')
    # ### end Alembic commands ###
